blank_lines_upper_bound = 2
fn_single_line = true
merge_imports = true
normalize_comments = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
wrap_comments = true